# Generated by Django 4.2.21 on 2025-06-13 12:21

from django.db import migrations, models
import django.db.models.deletion

def prepare_livreur_relation(apps, schema_editor):
    Livreur = apps.get_model('Agri_Connect_CI', 'Livreur')
    Utilisateur = apps.get_model('Agri_Connect_CI', 'Utilisateur')
    
    # Vérification des doublons (critique pour OneToOne)
    from collections import defaultdict
    user_counts = defaultdict(int)
    for livreur in Livreur.objects.all():
        user_counts[livreur.utilisateur_id] += 1
    
    for user_id, count in user_counts.items():
        if count > 1:
            raise ValueError(f"L'utilisateur {user_id} a {count} livreurs associés (doit être unique)")

    # Copie des données
    for livreur in Livreur.objects.all():
        livreur.utilisateur_new_id = livreur.utilisateur_id
        livreur.save()

class Migration(migrations.Migration):
    dependencies = [
        ('Agri_Connect_CI', '0002_alter_vehicule_capacite'),
    ]

    operations = [
        # 1. Ajout du nouveau champ temporaire
        migrations.AddField(
            model_name='livreur',
            name='utilisateur_new',
            field=models.OneToOneField(
                null=True,
                blank=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name='livreur_temp',
                to='Agri_Connect_CI.Utilisateur'
            ),
        ),
        
        # 2. Copie des données
        migrations.RunPython(prepare_livreur_relation),
        
        # 3. Suppression de l'ancien champ (dans une migration séparée)
        # migrations.RemoveField(...) <- À faire dans la migration suivante
    ]