# Generated by Django 4.2.21 on 2025-06-13 12:45

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Agri_Connect_CI', '0002_migrate_livreur_data'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='livreur',
            name='utilisateur_new',
        ),
        migrations.AlterField(
            model_name='livreur',
            name='utilisateur',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, unique=True),
        ),
    ]
