# Generated by Django 4.2.21 on 2025-06-13 12:47

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Agri_Connect_CI', '0003_remove_livreur_utilisateur_new_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='livreur',
            name='utilisateur',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='livreur', to=settings.AUTH_USER_MODEL),
        ),
    ]
