# Generated by Django 4.2.21 on 2025-06-13 12:29

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Agri_Connect_CI', '0003_prepare_livreur_relation'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='livreur',
            name='utilisateur_new',
        ),
        migrations.AlterField(
            model_name='livreur',
            name='utilisateur',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='livreur', to=settings.AUTH_USER_MODEL, verbose_name='Utilisateur'),
        ),
    ]
