# Generated by Django 4.2.21 on 2025-06-13 13:04

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Agri_Connect_CI', '0004_alter_livreur_utilisateur'),
    ]

    operations = [
        migrations.AlterField(
            model_name='producteur',
            name='utilisateur',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='producteur', to=settings.AUTH_USER_MODEL, verbose_name='Utilisateur'),
        ),
    ]
