# Generated by Django 4.2.21 on 2025-06-14 23:48

import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Agri_Connect_CI', '0005_alter_producteur_utilisateur'),
    ]

    operations = [
        migrations.CreateModel(
            name='DocumentProducteur',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type_document', models.CharField(choices=[('cni', "Carte Nationale d'Identité"), ('photo_ferme', 'Photo de la ferme'), ('autre', 'Autre document')], max_length=20)),
                ('fichier', models.FileField(upload_to='producteurs/documents/', validators=[django.core.validators.FileExtensionValidator(allowed_extensions=['jpg', 'jpeg', 'png', 'pdf'])])),
                ('date_upload', models.DateTimeField(auto_now_add=True)),
                ('description', models.CharField(blank=True, max_length=255, null=True)),
                ('producteur', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='documents', to='Agri_Connect_CI.producteur')),
            ],
            options={
                'verbose_name': 'Document producteur',
                'verbose_name_plural': 'Documents producteurs',
            },
        ),
    ]
