# Generated by Django 4.2.21 on 2025-06-15 20:51

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Agri_Connect_CI', '0006_documentproducteur'),
    ]

    operations = [
        migrations.CreateModel(
            name='TypeLivraison',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nom', models.CharField(max_length=50)),
                ('coefficient', models.DecimalField(decimal_places=2, max_digits=5)),
            ],
        ),
        migrations.CreateModel(
            name='TarifLivreur',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('prix', models.DecimalField(decimal_places=2, max_digits=10)),
                ('devise', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='Agri_Connect_CI.devise')),
                ('livreur', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Agri_Connect_CI.livreur')),
                ('type_livraison', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='Agri_Connect_CI.typelivraison')),
                ('vehicule', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='Agri_Connect_CI.vehicule')),
                ('zone', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='Agri_Connect_CI.zone')),
            ],
            options={
                'unique_together': {('livreur', 'type_livraison', 'zone'), ('livreur', 'vehicule', 'type_livraison', 'zone')},
            },
        ),
    ]
