# Generated by Django 4.2.21 on 2025-06-16 19:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Agri_Connect_CI', '0007_typelivraison_tariflivreur'),
    ]

    operations = [
        migrations.AddField(
            model_name='tariflivreur',
            name='libelle',
            field=models.CharField(default='Prix de base', max_length=100),
        ),
    ]
